accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('signup/',views.SignUpView.as_view(), name='signup'),
]

myapp/urls.py
from django.contrib import admin
from django.urls import include,path
from django.views.generic import RedirectView

urlpatterns = [
    path('port/', include('port.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', RedirectView.as_view(url='/port/')),
]

port/urls.py
from django.urls import path
from . import views

app_name = 'port'

urlpatterns =[
    path('',views.index,name='index'),
    path('<int:id>',views.detail,name='detail'),
    path('new',views.new, name='new'),
    path('create', views.create,name='create'),
    path('<int:id>/edit', views.edit,name='edit'),
    path('<int:id>/update', views.update,name='update'),
    path('<int:id>/delete', views.delete,name='delete'),
    path('<int:id>/confirm_delete', views.confirm_delete,name='confirm_delete'),
    path('<int:id>/des_edit', views.des_edit,name='des_edit'),
    path('<int:id>/des_update',views.des_update,name='des_update'),

]

accounts/models.py
from django.db import models

# Create your models here.

port/models.py
from django.db import models

#ポートフォリオに登録される銘柄の基本情報
class Security(models.Model):
    des = models.CharField(max_length=200)
    asset = models.CharField(max_length=200,null=True)
    price = models.CharField(max_length=200,null=True)
    position = models.CharField(max_length=200,null=True)

    def __str__(self):
        return self.des


#Securityクラスと関係する、企業の詳細情報.ForeignKeyはnameとし、SecurityのidとDescriptionのname_idが対応する
class Description(models.Model):
    name = models.ForeignKey(Security,on_delete=models.CASCADE,null=True)
    sector = models.CharField(max_length=255, null=True)
    country = models.CharField(max_length=225, null=True)
    business = models.CharField(max_length=225, null=True)

    def __str__(self):
        return str(self.name)

port/forms.py
from django import forms
from .models import Security,Description

#index.htmlの検索フォーム
class SearchForm(forms.Form):
    keyword = forms.CharField(label='Search by Asset Class ',max_length=100)


#index.html >> Addの新規銘柄追加フォーム
class SecurityForm(forms.ModelForm):
    class Meta:
        model = Security
        fields = ('des','asset','price','position')


#detail.htmlにおけるDescriptionモデル自動生成フォーム
class DescriptionForm(forms.ModelForm):
    class Meta:
        model = Description
        fields = ('name',)


#edit.html >> Rebalanceの銘柄編集フォーム
class RebalanceForm(forms.ModelForm):
    class Meta:
        model = Security
        fields = ('price','position')


#detail.html >> Edit Description Infoの情報編集フォーム
class Des_updateForm(forms.ModelForm):
    class Meta:
        model = Description
        fields = ('sector','country','business')

accounts/views.py
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy
from django.views import generic

#Signup用のViewを作成
class SignUpView(generic.CreateView):
    form_class = UserCreationForm
    success_url = reverse_lazy('login')
    template_name = 'accounts/signup.html'

port/views.py
from django.shortcuts import render, get_object_or_404
from .models import Security,Description
from .forms import SearchForm,RebalanceForm,SecurityForm,DescriptionForm,Des_updateForm



#index.htmlのページに対応
def index(request):
    searchForm = SearchForm(request.GET)
    if searchForm.is_valid():
        keyword = searchForm.cleaned_data['keyword']
        securities = Security.objects.filter(asset__contains=keyword)
    else:
        searchForm = SearchForm()
        securities = Security.objects.all()
    context = {
        'securities':securities,
        'searchform':searchForm,
    }
    return render(request, 'port/index.html',context)


#detail.htmlのページに対応
def detail(request,id):
    security = get_object_or_404(Security, pk=id)
    #Securityモデルに対応するDescriptionモデルのデータベースを自動生成
    try:
        description = Description.objects.get(name_id=id)
    except Description.DoesNotExist:
        descriptionForm = DescriptionForm({'name':id})
        description = descriptionForm.save()
    context = {
        'security':security,
        'description':description,
    }
    return render(request, 'port/detail.html',context)


#index.html >> Addボタン >> new.htmlに対応
def new(request):
    securityForm = SecurityForm()
    context = {
        'message':'Add a New Security',
        'securityForm':securityForm,
    }
    return render(request, 'port/new.html',context)

#new.htmlのフォームから入力を受け、実際にSecurityモデルにデータを追加
def create(request):
    if request.method == 'POST':
        securityForm = SecurityForm(request.POST)
        if securityForm.is_valid():
            security=securityForm.save()
    context = {
        'security': security,
    }
    #create URLでも、index.htmlを表示できるようindexファンクションの構成を付記。
    #Create後のurlを直接indexビューにするのがベストだが、、、、
    searchForm = SearchForm(request.GET)
    if searchForm.is_valid():
        keyword = searchForm.cleaned_data['keyword']
        securities = Security.objects.filter(asset__contains=keyword)
    else:
        searchForm = SearchForm()
        securities = Security.objects.all()
    context = {
        'securities':securities,
        'searchform':searchForm,
    }
    return render(request, 'port/index.html', context)


#detail.html >> Rebalanceボタン >> edit.htmlに対応
def edit(request,id):
    security = get_object_or_404(Security, pk=id)
    rebalanceForm = RebalanceForm(instance=security)
    context = {
        'message':'Rebalance a Position',
        'security':security,
        'rebalanceForm':rebalanceForm,
    }
    return render(request, 'port/edit.html',context)

#edit.htmlのフォームから入力を受け、実際にSecurityモデルのデータを編集
def update(request,id):
    if request.method == 'POST':
        security = get_object_or_404(Security, pk=id)
        rebalanceForm = RebalanceForm(request.POST, instance=security)
        if rebalanceForm.is_valid():
            rebalanceForm.save()
    try:
        description = Description.objects.get(name_id=id)
    except Description.DoesNotExist:
        description = None
    context = {
        'security':security,
        'description':description,
    }
    return render(request, 'port/detail.html',context)


#detail.html >> Removeボタン >> confirm_delete.htmlに対応
def confirm_delete(request,id):
    security = get_object_or_404(Security, pk=id)
    context ={
        'security':security,
    }
    return render(request, 'port/confirm_delete.html',context)

#confirm_delete.htmlの入力を受けて実際にecurityモデルからデータを消去
def delete(request,id):
    security = get_object_or_404(Security, pk=id)
    security.delete()
    securities = Security.objects.all()
    context = {
        'message':'Delete Security ' + str(id),
        'securities':securities,
    }
    return render(request, 'port/index.html',context)


#detail.html >> Edit Description Infoリンク >> des_edit.htmlに対応
def des_edit(request,id):
    security = get_object_or_404(Description,name_id=id)
    des_updateForm = Des_updateForm(instance=security)
    if des_updateForm.is_valid():
        des_updateForm.save()
    context = {
        'message':'Edit Description info',
        'security':security,
        'des_updateForm':des_updateForm,
    }
    return render(request, 'port/des_edit.html',context)

#des_edit.htmlの入力を受け、実際にDescriptionモデルのデータを編集
def des_update(request,id):
    if request.method == 'POST':
        security = get_object_or_404(Security, pk=id)
        description = get_object_or_404(Description,name_id=id)
        des_updateForm = Des_updateForm(request.POST,instance=description)
        if des_updateForm.is_valid():
            des_updateForm.save()
    context = {
        'description':description,
        'security':security,
        'des_updateForm':des_updateForm,
    }
    return render(request,'port/detail.html',context)

accounts/templates/accounts/signup.html
{% extends 'layout.html' %}
{% block content %}

<h1>Sign Up</h1>
<section class='common-form'>
    <form method='post'>
        {% csrf_token %}
        {{form.as_p}}
        <button type='submit' class='btn btn-outline-primary'>SIgn Up</button>
    </form>
</section>
{% endblock %}

port/templates/port/base.html
<!DOCTYPE html>
<html>
    <!--metaデータおよびbootstrapの導入.合わせてタイトルの設定とCSSの適用-->
    <head>
        <meta charset='utf-8'>
        <meta name='viewport' content='width=device-width, initial-scale=1, shrink-to-fit=no'>
        <title>My Portfolio</title>
        <link rel='stylesheet' href='https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css'&gt;>
        <style>
          body {padding: 80px;}
          .price {margin-right : 30px;}
          .table {text-align:center;}
        </style>
    </head>
    <!--固定バーおよびアプリロゴの設定-->
    <body>
        <nav class='navbar navbar-expand-md navbar-dark bg-dark fixed-top'>
            <a class='navbar-brand' href='{% url "port:index" %}'>PORT</a>
        </nav>
        <div class='container'>
            {% block content %}
            {% endblock %}
        </div>
    </body>
</html>

port/templates/port/confirm_delete.html
{% extends 'layout.html' %}
{% block content %}
<header>
    <h1>Remove "{{security}}" from Port </h1>
    <p><b>ARE YOU SURE TO REMOVE THE SECURITY FROM YOUR PORTFOLIO?</b></p>
</header>
<main>
    <form action='' method='post'>
      {% csrf_token %}
      <div class="button">
        <p><a href="{% url 'port:delete' security.id %}" class='btn btn-outline-primary'>Remove</a></p>
        <p><a href="JavaScript:history.back()"class='btn btn-outline-secondary btn-sm'>Back</a></p>
      </div>
    </form>
</main>
{% endblock %}

port/templates/port/des_edit.html
{% extends 'layout.html' %}
{% load bootstrap4 %}

{% block content %}
<header>
    <h1>{{message}}</h1>
</header>
<main>
    <form action='{% url "port:des_update" security.name_id %}' method='post' class='form'>
      {% csrf_token %}
      {% bootstrap_form des_updateForm layout='horizontal' %}
      <div class="button">
        <p><button type='submit' class='btn btn-outline-primary'> Save </button></p>
        <p><a href="{% url 'port:detail' security.name_id %}" class = 'btn btn-outline-secondary btn-sm'>Back</a></p>
      </div>
    </form>
</main>
{% endblock %}

port/templates/port/detail.html
{% extends 'layout.html' %}
{% block content %}
<header>
  <h1>{{security.des}} <a href="{% url 'port:des_edit' security.id %}" class='btn btn-link'>Edit Description info</a></h1>
  <br>
  <h4><span class='price'>Price : {{security.price}}</span> Position  : {{security.position}}</h4>
  <br>
</header>
  <h5>Asset Class : {{security.asset}}</h5>
  <div class=description>
    <hr color='	navy' noshade>
    <p>Sector : {{description.sector}}</p>
    <p>Country : {{description.country}}</p>
    <br>
    <p>[Business Overview]</p>
    <p>{{description.business}}</p>
  </div>
  <div class="button">
    <!--adminとしてログインしてる時のみ銘柄の編集、削除ボタンを表示-->
    {% if user.is_authenticated %}
      <p>
      <a href="{% url 'port:edit' security.id %}" class='btn btn-outline-primary'>Rebalance</a>
      <a href="{% url 'port:confirm_delete' security.id %}" class='btn btn-outline-primary'>Remove</a>
      </p>
    {% endif %}
    <p><a href="{% url 'port:index' %}" class='btn btn-outline-secondary btn-sm'>Back</a></p>
  </div>
</main>
{% endblock %}

port/templates/port/edit.html
{% extends 'layout.html' %}
{% load bootstrap4 %}

{% block content %}
<header>
    <h1>{{message}}</h1>
</header>
<main>
    <form action='{% url "port:update" security.id %}' method='post' class='form'>
      {% csrf_token %}
      {% bootstrap_form rebalanceForm layout='horizontal' %}
      <div class="button">
        <p><button type='submit' class='btn btn-outline-primary'> Save </button></p>
        <p><a href="{% url 'port:detail' security.id %}" class = 'btn btn-outline-secondary btn-sm'>Back</a></p>
      </div>
    </form>
</main>
{% endblock %}

port/templates/port/index.html
{% extends 'layout.html' %}
{% block content %}
<header>
    <h1>Port Management</h1>
    <br>
    {% if searchform %}
      <form action = '{% url "port:index" %}' method='get'>
        <div class = 'form-group'>
          <p>{{searchform}}</p>
          <p class=search-button>
            <input type = 'submit' class = 'btn btn-outline-primary' value='Search'>
            <a href="{% url 'port:index' %}" class='btn btn-outline-secondary'> Clear</a>
          </p>
        </div>
      </form>
    {% endif %}
</header>
<main>
    <div class='table'>
    <table class='table table-hover'>
      <tr>
        <th>Security</th><th>Asset</th><th>Price</th><th>Position</th>
      </tr>
      {% for security in securities %}
        <tr>
          <td><a href="{% url 'port:detail' security.pk %}">{{security.des}}</a></td>
          <td>{{security.asset}}</td>
          <td>{{security.price}}</td>
          <td>{{security.position}}</td>
        </tr>
      {% endfor %}
    </table>
    </div>
    <!--adminとしてログインしてる時のみ銘柄の追加ボタンを表示-->
    {% if user.is_authenticated %}
        <div class="button">
            <p><a href="{% url 'port:new' %}" class='btn btn-outline-primary' >Add</a></p>
        </div>
    {% endif %}
</main>
{% endblock %}

port/templates/port/new.html
{% extends 'layout.html' %}
{% load bootstrap4 %}

{% block content %}
<header>
    <h1>{{message}}</h1>
</header>
<main>
    <form action='{% url "port:create" %}' method='post' class='form'>
      {% csrf_token %}
      {% bootstrap_form securityForm layout='horizontal' %}
      <div class="button">
        <p><button type='submit' class='btn btn-outline-primary'> Add </button></p>
        <p><a href="{% url 'port:index' %}" class = 'btn btn-outline-secondary btn-sm'>Back</a></p>
      </div>
    </form>
</main>
{% endblock %}

templates/layout.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset='utf-8'>
        <meta name='viewport' content='width=device-width, initial-scale=1, shrink-to-fit=no'>
        <link rel='stylesheet' href='https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css' integrity='sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm' crossorigin='anonymous'>
        <!--レスポンシブデザインにも対応-->
        <style>
            body {padding-top: 100px;}
            .search-button{text-align: right;}
            .price {margin-right : 30px;}
            .table {
              text-align:center;
              max-width: 100%;
            }
            html {
              max-width: 100%;
              margin: 0 auto;
            }
            main{
              padding-top: 30px;
            }
            .button{
              padding-top: 50px;
            }
            .navbar-nav{text-align:left;}
          @media (max-width:767px){
            html{
              width:auto;
            }
          }
        </style>
        <title>PORT</title>
    </head>
    <body>
        <nav class='navbar navbar-expand navbar-dark bg-dark fixed-top'>
            <a class='navbar-brand' href='{% url "port:index" %}'>PORT</a>
            <ul class='navbar-nav'>
                <!--ログイン中、ログアウト中でナビバーに出す表示を変更-->
                {% if user.is_authenticated %}
                    <li class='nav-itme'>
                        <span class='navbar-text'>{{ user }} - </span>
                    </li>
                    <li class='nav-item'>
                        <a href='{% url "logout" %}' class='logout nav-link'>Logout</a>
                    </li>
                {% else %}
                    <li class='nav-itme'>
                      <a href='{% url "login" %}' class='login nav-link'>Login</a>
                    </li>
                    <li class='nav-item'>
                      <a href='{% url "accounts:signup" %}' class='signup nav-link'>Sign Up</a>
                    </li>
                {% endif %}
            </ul>
            </dlv>
        </nav>
        <div class='container'>
            {% block content %}
            {% endblock %}
       </div>
    </body>
</html>